<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${base_height/2 + wheel_radius/2}" rpy="0.0 0.0 0.0"/>
    </joint>
    <joint name="base_to_front_right_engine" type="fixed">
        <origin xyz="${base_length/4} ${-1*(base_width/2-engine_length/2)} ${-1*(base_height/2 + engine_height/2)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="front_right_engine"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>
    <joint name="front_right_engine_to_front_right_shaft" type="continuous">
        <parent link="front_right_engine"/>
        <child link="front_right_shaft"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 ${-1*(engine_length/2 + 0.0001 + shaft_length/2)} 0" rpy="0 0 0"/>
    </joint>
    <joint name="front_right_shaft_to_front_right_wheel" type="fixed">
        <parent link="front_right_shaft"/>
        <child link="front_right_wheel"/>
        <origin xyz="0 ${-1*(shaft_length/2 + wheel_length/2)} 0" rpy="0 0 0"/>
    </joint>
    <joint name="base_to_front_left_engine" type="fixed">
        <origin xyz="${base_length/4} ${(base_width/2-engine_length/2)} ${-1*(base_height/2 + engine_height/2)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="front_left_engine"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>
    <joint name="front_left_engine_to_front_left_shaft" type="continuous">
        <parent link="front_left_engine"/>
        <child link="front_left_shaft"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 ${(engine_length/2 + 0.0001 + shaft_length/2)} 0" rpy="0 0 0"/>
    </joint>
    <joint name="front_left_shaft_to_front_left_wheel" type="fixed">
        <parent link="front_left_shaft"/>
        <child link="front_left_wheel"/>
        <origin xyz="0 ${(shaft_length/2 + wheel_length/2)} 0" rpy="0 0 0"/>
    </joint>
    <joint name="base_to_rear_right_engine" type="fixed">
        <origin xyz="${-base_length/4} ${-1*(base_width/2-engine_length/2)} ${-1*(base_height/2 + engine_height/2)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="rear_right_engine"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>
    <joint name="rear_right_engine_to_rear_right_shaft" type="continuous">
        <parent link="rear_right_engine"/>
        <child link="rear_right_shaft"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 ${-1*(engine_length/2 + 0.0001 + shaft_length/2)} 0" rpy="0 0 0"/>
    </joint>
    <joint name="rear_right_shaft_to_rear_right_wheel" type="fixed">
        <parent link="rear_right_shaft"/>
        <child link="rear_right_wheel"/>
        <origin xyz="0 ${-1*(shaft_length/2 + wheel_length/2)} 0" rpy="0 0 0"/>
    </joint>
    <joint name="base_to_rear_left_engine" type="fixed">
        <origin xyz="${-base_length/4} ${base_width/2-engine_length/2} ${-1*(base_height/2 + engine_height/2)}" rpy="0.0 0.0 0.0"/>
        <parent link="base_link"/>
        <child link="rear_left_engine"/>
        <axis xyz="0.0 0.0 0.0"/>
    </joint>
    <joint name="rear_left_engine_to_rear_left_shaft" type="continuous">
        <parent link="rear_left_engine"/>
        <child link="rear_left_shaft"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 ${engine_length/2 + 0.0001 + shaft_length/2} 0" rpy="0 0 0"/>
    </joint>
    <joint name="rear_left_shaft_to_rear_left_wheel" type="fixed">
        <parent link="rear_left_shaft"/>
        <child link="rear_left_wheel"/>
        <origin xyz="0 ${shaft_length/2 + wheel_length/2} 0" rpy="0 0 0"/>
    </joint>
</robot>